/**
 * I.audio — types for public/audio/manifest.json, generated by
 * scripts/audio/generate-sfx.mjs (the single authority for the sound set).
 * The runtime engine and tests validate the generated JSON against this
 * shape via validateManifest() — fail loud on drift (V10 spirit).
 */

export const SOUND_CATEGORIES = [
  'footsteps',
  'jump',
  'shoot',
  'impact',
  'explosion',
  'destruction',
  'water',
  'ambience',
  'ui',
  'player',
  'vehicle', // T64 — engine loops, skid, crashes, doors, horns
  'music',
] as const

export type SoundCategory = (typeof SOUND_CATEGORIES)[number]

export interface SoundDef {
  /** unique id, `<group>-<n>` for round-robin members */
  id: string
  /** site-root absolute path, e.g. /audio/sfx/footsteps/footstep-walk-grass-1.mp3 */
  path: string
  category: SoundCategory
  /** seamless loop asset (ambience beds, music, heartbeat) */
  loop: boolean
  /** per-asset volume trim 0..1, applied on top of the bus gain */
  volume: number
  /** true = played through a PannerNode at a world position (meters) */
  positional: boolean
  /** variation group for round-robin; equals id for singletons */
  roundRobin: string
}

export interface AudioManifest {
  version: 1
  sounds: SoundDef[]
}

/** structural validation — throws with a precise message on any drift */
export function validateManifest(data: unknown): AudioManifest {
  if (typeof data !== 'object' || data === null) throw new Error('manifest: not an object')
  const m = data as Record<string, unknown>
  if (m.version !== 1) throw new Error(`manifest: version ${String(m.version)} !== 1`)
  if (!Array.isArray(m.sounds)) throw new Error('manifest: sounds is not an array')
  const ids = new Set<string>()
  for (const raw of m.sounds) {
    const s = raw as Record<string, unknown>
    const where = `manifest sound ${JSON.stringify(s.id ?? '<no id>')}`
    if (typeof s.id !== 'string' || !/^[a-z0-9-]+$/.test(s.id)) throw new Error(`${where}: bad id`)
    if (ids.has(s.id)) throw new Error(`${where}: duplicate id`)
    ids.add(s.id)
    if (typeof s.path !== 'string' || !s.path.startsWith('/audio/')) throw new Error(`${where}: bad path`)
    if (!SOUND_CATEGORIES.includes(s.category as SoundCategory)) throw new Error(`${where}: bad category ${String(s.category)}`)
    if (typeof s.loop !== 'boolean') throw new Error(`${where}: loop not boolean`)
    if (typeof s.volume !== 'number' || s.volume < 0 || s.volume > 1) throw new Error(`${where}: volume out of [0,1]`)
    if (typeof s.positional !== 'boolean') throw new Error(`${where}: positional not boolean`)
    if (typeof s.roundRobin !== 'string' || s.roundRobin.length === 0) throw new Error(`${where}: bad roundRobin`)
    if (!s.id.startsWith(s.roundRobin as string)) throw new Error(`${where}: roundRobin '${String(s.roundRobin)}' is not an id prefix`)
  }
  return data as AudioManifest
}
